name: pytorch
channels:
  - defaults
dependencies:
  - sip==6.6.2=py37h6a678d5_0
  - qt-main==5.15.2=h327a75a_6
  - libbrotlienc==1.0.9=h5eee18b_7
  - libffi==3.3=he6710b0_2
  - kiwisolver==1.4.2=py37h295c915_0
  - threadpoolctl==2.2.0=pyh0d69192_0
  - libsodium==1.0.18=h7b6447c_0
  - libblas==3.9.0=12_linux64_mkl
  - nss==3.74=h0370c37_0
  - libxslt==1.1.35=h4e12654_0
  - openssl
  - ld_impl_linux-64==2.38=h1181459_1
  - intel-openmp==2021.4.0=h06a4308_3561
  - jsonschema==4.4.0=py37h06a4308_0
  - charset-normalizer==2.0.4=pyhd3eb1b0_0
  - six==1.16.0=pyhd3eb1b0_1
  - pcre==8.45=h295c915_0
  - wcwidth==0.2.5=pyhd3eb1b0_0
  - python==3.7.13=h12debd9_0
  - libwebp-base==1.2.2=h7f8727e_0
  - testpath==0.6.0=py37h06a4308_0
  - libtiff==4.2.0=h2818925_1
  - libcblas==3.9.0=12_linux64_mkl
  - brotli==1.0.9=h5eee18b_7
  - pip==22.1.2=py37h06a4308_0
  - backcall==0.2.0=pyhd3eb1b0_0
  - gnutls==3.6.15=he1e5248_0
  - qtconsole==5.3.2=py37h06a4308_0
  - libxkbcommon==1.0.1=hfa300c1_0
  - jupyter_console==6.4.3=pyhd3eb1b0_0
  - torchvision
  - ninja==1.10.2=h06a4308_5
  - python_abi==3.7=2_cp37m
  - graphviz==2.50.0=h3cd0ef9_0
  - markupsafe==2.1.1=py37h7f8727e_0
  - pytorch-mutex==1.0=cuda
  - mkl_random==1.2.2=py37h51133e4_0
  - tk==8.6.12=h1ccaba5_0
  - jedi==0.18.1=py37h06a4308_1
  - zstd==1.5.2=ha4553b6_0
  - jupyterlab_widgets==1.0.0=pyhd3eb1b0_1
  - libgcc-ng==11.2.0=h1234567_1
  - parso==0.8.3=pyhd3eb1b0_0
  - ffmpeg==4.3=hf484d3e_0
  - libuv==1.40.0=h7b6447c_0
  - expat==2.4.4=h295c915_0
  - prompt_toolkit==3.0.20=hd3eb1b0_0
  - gstreamer==1.14.0=h28cd5cc_2
  - dbus==1.13.18=hb2f20db_0
  - traitlets==5.1.1=pyhd3eb1b0_0
  - lame==3.100=h7b6447c_0
  - packaging==21.3=pyhd3eb1b0_0
  - pygments==2.11.2=pyhd3eb1b0_0
  - font-ttf-source-code-pro==2.030=hd3eb1b0_0
  - joblib==1.1.0=pyhd3eb1b0_0
  - python-graphviz==0.20.1=py37h06a4308_0
  - psutil==5.9.0=py37h5eee18b_0
  - pyqt==5.15.7=py37h6a678d5_1
  - librsvg==2.54.4=h19fe530_0
  - urllib3==1.26.11=py37h06a4308_0
  - pytz==2022.1=py37h06a4308_0
  - qtwebkit==5.212=h4eab89a_4
  - glib==2.69.1=h4ff587b_1
  - importlib_resources==5.2.0=pyhd3eb1b0_1
  - soupsieve==2.3.1=pyhd3eb1b0_0
  - pickleshare==0.7.5=pyhd3eb1b0_1003
  - gts==0.7.6=hb67d8dd_3
  - setuptools==61.2.0=py37h06a4308_0
  - font-ttf-ubuntu==0.83=h8b1ccd4_0
  - typing_extensions==4.7.1=pyha770c72_0
  - libidn2==2.3.2=h7f8727e_0
  - libgfortran4==7.5.0=ha8ba4b0_17
  - defusedxml==0.7.1=pyhd3eb1b0_0
  - bottleneck==1.3.5=py37h7deecbd_0
  - nbconvert==6.4.4=py37h06a4308_0
  - nest-asyncio==1.5.5=py37h06a4308_0
  - pyzmq==23.2.0=py37h6a678d5_0
  - python-annoy==1.17.0=py37hd23a5d3_4
  - blas==1.0=mkl
  - pyopenssl==22.0.0=pyhd3eb1b0_0
  - zeromq==4.3.4=h2531618_0
  - pytorch
  - jupyter==1.0.0=py37h06a4308_8
  - zipp==3.8.0=py37h06a4308_0
  - libbrotlidec==1.0.9=h5eee18b_7
  - brotli-bin==1.0.9=h5eee18b_7
  - python-dateutil==2.8.2=pyhd3eb1b0_0
  - jinja2==3.0.3=pyhd3eb1b0_0
  - debugpy==1.5.1=py37h295c915_0
  - ninja-base==1.10.2=hd09550d_5
  - fonttools==4.25.0=pyhd3eb1b0_0
  - qt-webengine==5.15.9=hd2b0992_4
  - krb5==1.19.2=hac12032_0
  - libunistring==0.9.10=h27cfd23_0
  - attrs==21.4.0=pyhd3eb1b0_0
  - gobject-introspection==1.72.0=py37hbb6d50b_0
  - mistune==0.8.4=py37h14c3975_1001
  - entrypoints==0.4=py37h06a4308_0
  - websocket-client==0.58.0=py37h06a4308_4
  - scipy==1.7.3=py37hc147768_0
  - pexpect==4.8.0=pyhd3eb1b0_3
  - pyrsistent==0.18.0=py37heee7806_0
  - pillow==9.2.0=py37hace64e9_1
  - json5==0.9.6=pyhd3eb1b0_0
  - qtpy==2.2.0=py37h06a4308_0
  - ipython==7.31.1=py37h06a4308_1
  - importlib-metadata==4.11.3=py37h06a4308_0
  - openh264==2.1.1=h4ff587b_0
  - send2trash==1.8.0=pyhd3eb1b0_1
  - notebook==6.4.12=py37h06a4308_0
  - requests==2.28.1=py37h06a4308_0
  - _openmp_mutex==5.1=1_gnu
  - freetype==2.11.0=h70c0345_0
  - pandocfilters==1.5.0=pyhd3eb1b0_0
  - fonts-conda-ecosystem==1=hd3eb1b0_0
  - ipython_genutils==0.2.0=pyhd3eb1b0_1
  - lcms2==2.12=h3be6417_0
  - fribidi==1.0.10=h7b6447c_0
  - libbrotlicommon==1.0.9=h5eee18b_7
  - libpng==1.6.39=h5eee18b_0
  - _libgcc_mutex==0.1=main
  - wheel==0.37.1=pyhd3eb1b0_0
  - libclang==10.0.1=default_hb85057a_2
  - libtool==2.4.6=h6a678d5_1009
  - readline==8.1.2=h7f8727e_1
  - cycler==0.11.0=pyhd3eb1b0_0
  - nbformat==5.5.0=py37h06a4308_0
  - xz==5.2.5=h7f8727e_1
  - mkl-service==2.4.0=py37h7f8727e_0
  - nbclient==0.5.13=py37h06a4308_0
  - cudatoolkit=11.4
  - ipykernel==6.15.2=py37h06a4308_0
  - pixman==0.40.0=h7f8727e_1
  - ply==3.11=py37_0
  - babel==2.9.1=pyhd3eb1b0_0
  - jupyterlab==3.4.4=py37h06a4308_0
  - nbclassic==0.3.5=pyhd3eb1b0_0
  - gst-plugins-base==1.14.0=h8213a91_2
  - atk-1.0==2.36.0=ha1a6a79_0
  - prompt-toolkit==3.0.20=pyhd3eb1b0_0
  - pandas==1.3.5=py37h8c16a72_0
  - certifi
  - lz4-c==1.9.3=h295c915_1
  - bzip2==1.0.8=h7b6447c_0
  - idna==3.3=pyhd3eb1b0_0
  - libpq==12.9=h16c4e8d_3
  - beautifulsoup4==4.11.1=py37h06a4308_0
  - jupyter_core==4.10.0=py37h06a4308_0
  - libxcb==1.15=h7f8727e_0
  - fontconfig==2.13.1=h6c09931_0
  - cryptography==37.0.1=py37h9ce1e76_0
  - graphite2==1.3.14=h295c915_1
  - fonts-anaconda==1=h8fa9717_0
  - pycparser==2.21=pyhd3eb1b0_0
  - nspr==4.33=h295c915_0
  - libedit==3.1.20210910=h7f8727e_0
  - libxml2==2.9.14=h74e7548_0
  - ptyprocess==0.7.0=pyhd3eb1b0_2
  - jupyter_client==7.1.2=pyhd3eb1b0_0
  - argon2-cffi==20.1.0=py37h27cfd23_1
  - decorator==5.1.1=pyhd3eb1b0_0
  - munkres==1.1.4=py_0
  - libevent==2.1.12=h8f2d780_0
  - anyio==3.5.0=py37h06a4308_0
  - pyparsing==3.0.4=pyhd3eb1b0_0
  - libllvm10==10.0.1=hbcb73fb_5
  - libwebp==1.2.2=h55f646e_0
  - mkl==2021.4.0=h06a4308_640
  - torchaudio
  - jupyterlab_server==2.12.0=py37h06a4308_0
  - webencodings==0.5.1=py37_1
  - ca-certificates
  - libiconv==1.16=h7f8727e_2
  - gtk2==2.24.33=h73c1081_2
  - importlib_metadata==4.11.3=hd3eb1b0_0
  - prometheus_client==0.14.1=py37h06a4308_0
  - ipywidgets==7.6.5=pyhd3eb1b0_1
  - giflib==5.2.1=h7b6447c_0
  - gmp==6.2.1=h295c915_3
  - numpy-base==1.21.5=py37ha15fc14_3
  - pango==1.50.7=h05da053_0
  - mkl_fft==1.3.1=py37hd3c417c_0
  - libstdcxx-ng==11.2.0=h1234567_1
  - harfbuzz==4.3.0=hf52aaf7_1
  - widgetsnbextension==3.5.2=py37h06a4308_0
  - cairo==1.16.0=h19f5f5c_2
  - jupyter_server==1.18.1=py37h06a4308_0
  - libgomp==11.2.0=h1234567_1
  - nettle==3.7.3=hbbd107a_1
  - jpeg==9e=h7f8727e_0
  - numpy==1.21.5=py37h6c91a56_3
  - cffi==1.15.1=py37h74dc2b5_0
  - bleach==4.1.0=pyhd3eb1b0_0
  - font-ttf-inconsolata==2.001=hcb22688_0
  - brotlipy==0.7.0=py37h27cfd23_1003
  - icu==58.2=he6710b0_3
  - libgd==2.3.3=h695aa2c_1
  - jupyterlab_pygments==0.1.2=py_0
  - toml==0.10.2=pyhd3eb1b0_0
  - pysocks==1.7.1=py37_1
  - gdk-pixbuf==2.42.10=h5eee18b_0
  - pyqt5-sip==12.11.0=py37h6a678d5_1
  - libgfortran-ng==7.5.0=ha8ba4b0_17
  - torchmetrics==0.11.4=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono==2.37=hd3eb1b0_0
  - python-fastjsonschema==2.16.2=py37h06a4308_0
  - tornado==6.1=py37h27cfd23_0
  - terminado==0.13.1=py37h06a4308_0
  - libuuid==1.0.3=h7f8727e_2
  - libtasn1==4.16.0=h27cfd23_0
  - ncurses==6.3=h5eee18b_3
  - sqlite==3.38.5=hc218d9a_0
  - zlib==1.2.13=h5eee18b_0
  - numexpr==2.8.3=py37h807cd23_0
  - scikit-learn==1.0.2=py37hf9e9bfc_0
  - sniffio==1.2.0=py37h06a4308_1
  - tensorboard
  - tensorflow
prefix: /users/ryan30/.conda/envs/pytorch
